import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "../styles/globals.css";
import { cn } from "@/shared/lib/utils";
import AppProvider from "@/shared/providers/AppProvider";

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Inicio de Sesión",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" className={cn("font-sans", geist.variable)}>
      <body suppressHydrationWarning>
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
